@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "User" as U
participant "Users Manager" as UM
participant "Users DB" as DB

activate U
U -> UM : 1.0 כניסה לדף ההתחברות
UM -> U : 1.1 החזרת דף הכניסה

group sd Loop
U -> UM : 2.0 הזנת דוא"ל וסיסמה
activate UM
UM -> DB : 2.1 שליפת המשתמש לפי הדוא״ל
activate DB
DB --> UM : 2.2 החזרת פרטי המשתמש
deactivate DB
UM -> UM : 2.3 השוואת הסיסמה המוצפנת
UM -> U : 2.4 הצגת שגיאה אם הפרטים שגויים
deactivate UM
end

UM -> UM : 3.0 יצירת אסימון הזדהות עם ההרשאות
UM -> U : 3.1 פתיחת הממשק המותאם להרשאות המשתמש
deactivate U
@enduml