@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "משתמש" as U
participant "Users Manager" as UM
participant "Users DB" as DB

activate U
U -> UM : צעד 1 - המשתמש מזין דוא"ל וסיסמה
U -> UM : צעד 2 - המשתמש לוחץ על כפתור התחברות

group sd Loop
activate UM
UM -> DB : צעד 3.1 - המערכת שולפת את המשתמש לפי הדוא״ל
activate DB
DB --> UM : צעד 3.2 - מסד הנתונים מחזיר את פרטי המשתמש
deactivate DB
UM -> UM : צעד 3 - המערכת מאמתת את פרטי ההתחברות\nמול מסד הנתונים
UM -> U : הסתעפות א.1 בצעד 3 - המערכת מציגה הודעת שגיאה מתאימה
UM -> U : הסתעפות א.2 בצעד 3 - חזרה לצעד 1
deactivate UM
end

activate UM
UM -> U : צעד 4 - המערכת מעבירה את המשתמש לממשק\nהמותאם עבורו (לקוח / ספר / מנהל)
deactivate UM
deactivate U
@enduml