@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "לקוח" as C
participant "Appointments Manager" as AM
participant "Appointments DB" as DB

activate C
C -> AM : צעד 1 - הלקוח נכנס לאזור "התורים שלי"
activate AM
AM -> DB : צעד 2 - המערכת שולפת את התורים העתידיים\nשל הלקוח ממסד הנתונים
activate DB
DB --> AM : צעד 2.1 - מסד הנתונים מחזיר את רשימת התורים
deactivate DB

group sd Loop
AM -> C : צעד 3 - המערכת בודקת ומציגה את פירוט\nהתורים הקיימים
AM -> C : הסתעפות א.1 בצעד 3 - המערכת מציגה הודעה "אין תורים קיימים"
end
deactivate AM
deactivate C
@enduml