@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "לקוח" as C
participant "Appointments Manager" as AM
participant "Appointments DB" as DB

activate C
C -> AM : צעד 1 - הלקוח נכנס לאזור "שינוי תור"
activate AM
AM -> DB : צעד 2.1 - המערכת שולפת את התורים הקיימים
activate DB
DB --> AM : צעד 2.2 - מסד הנתונים מחזיר את רשימת התורים
deactivate DB

group sd Loop
AM -> C : צעד 2 - המערכת בודקת ומציגה את רשימת\nהתורים הקיימים של הלקוח
AM -> C : הסתעפות א.1 בצעד 2 - המערכת מציגה הודעה "אין תורים קיימים"
deactivate AM
end

C -> AM : צעד 3 - הלקוח לוחץ על כפתור שינוי ליד תור קיים\nובוחר תאריך חדש מתוך לוח השנה

group sd Loop
activate AM
AM -> DB : צעד 4.1 - המערכת שולפת את התורים התפוסים\nבתאריך החדש
activate DB
DB --> AM : צעד 4.2 - מסד הנתונים מחזיר את רשימת התורים
deactivate DB
AM -> C : צעד 4 - המערכת בודקת ומציגה שעות פנויות\nבלבד לתאריך החדש
AM -> C : הסתעפות ב.1 בצעד 4 - המערכת מציגה הודעה כי אין\nשעות פנויות בתאריך זה
AM -> C : הסתעפות ב.2 בצעד 4 - חזרה לצעד 3
deactivate AM
end

C -> AM : צעד 5 - הלקוח בוחר שעה פנויה מבוקשת ולוחץ על אישור
activate AM
AM -> DB : צעד 6 - המערכת מפנה את המועד הישן לכלל\nהלקוחות ומעדכנת את התור החדש
activate DB
DB --> AM : צעד 6.1 - מסד הנתונים מאשר את העדכון
deactivate DB
AM -> C : צעד 7 - המערכת מציגה הודעת אישור שינוי תור
deactivate AM
deactivate C
@enduml