@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "משתמש" as U
participant "Users Manager" as UM
participant "Users DB" as DB

activate U
U -> UM : צעד 1 - המשתמש לוחץ על אפשרות "פרופיל אישי"
activate UM
UM -> DB : צעד 2.1 - המערכת פונה למסד הנתונים
activate DB
DB --> UM : צעד 2.2 - מסד הנתונים מחזיר את הפרטים
deactivate DB
UM -> U : צעד 2 - המערכת שולפת ומציגה את הפרטים\nהאישיים הקיימים ממסד הנתונים
deactivate UM

group sd Loop
U -> UM : צעד 3 - המשתמש מעדכן את הפרטים המבוקשים\nולוחץ על כפתור "שמירת עדכון"
activate UM
UM -> UM : צעד 4 - המערכת מוודאת שהפרטים שהוזנו\nתקינים ומלאים
UM -> U : הסתעפות א.2 בצעד 4 - המערכת מציגה הודעת שגיאה מתאימה
UM -> U : הסתעפות א.3 בצעד 4 - חזרה לצעד 3
deactivate UM
end

activate UM
UM -> DB : צעד 5 - המערכת מעדכנת את הנתונים במסד הנתונים
activate DB
DB --> UM : צעד 5.1 - מסד הנתונים מאשר את העדכון
deactivate DB
UM -> U : צעד 6 - המערכת מציגה הודעת אישור על\nעדכון הפרטים בהצלחה
deactivate UM
deactivate U
@enduml