@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "מנהל ראשי" as A
participant "Users Manager" as UM
participant "Users DB" as DB

activate A
A -> UM : צעד 1 - המנהל הראשי לוחץ על אפשרות ניהול משתמשים
activate UM
UM -> DB : צעד 2.1 - המערכת פונה למסד הנתונים
activate DB
DB --> UM : צעד 2.2 - מסד הנתונים מחזיר את רשימת המשתמשים
deactivate DB
UM -> A : צעד 2 - המערכת מבצעת שליפת והצגת רשימת\nהמשתמשים ממסד הנתונים
deactivate UM

A -> UM : צעד 3 - המנהל הראשי מבצע בחירת משתמש\nועדכון הרשאות
activate UM
UM -> A : צעד 4 - המערכת מבצעת הצגת חלון וכפתור\nאישור שינוי הרשאות
deactivate UM

group sd Loop
A -> UM : צעד 5 - המנהל הראשי מאשר את השינוי בחלון האישור
activate UM
UM -> DB : צעד 6 - המערכת מבצעת עדכון ההרשאות\nבמסד הנתונים
activate DB
DB --> UM : צעד 6.1 - מסד הנתונים מאשר את העדכון
deactivate DB
UM -> A : צעד 7 - המערכת מבצעת הצגת הודעת אישור\nעל עדכון השינוי
UM -> A : הסתעפות א.2 בצעד 5 - התהליך מסתיים ללא ביצוע שינוי\nבהרשאות המשתמש
deactivate UM
end
deactivate A
@enduml