@startuml
hide footbox
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam defaultFontSize 13
skinparam sequence {
ArrowColor black
ArrowFontColor black
ActorBorderColor black
ActorBackgroundColor #66CCFF
LifeLineBorderColor black
LifeLineBackgroundColor #99DDFF
ParticipantBorderColor black
ParticipantBackgroundColor #66CCFF
ParticipantFontColor black
ParticipantFontSize 13
GroupBorderColor black
GroupBackgroundColor white
GroupHeaderFontColor black
}

actor "מנהל ראשי" as A
participant "Appointments Manager" as AM
participant "Appointments DB" as DB

activate A
A -> AM : 1.0 כניסה לאזור "ניהול תורים"
activate AM
AM -> DB : 1.1 שליפת כלל התורים במערכת
activate DB
DB --> AM : 1.2 החזרת רשימת התורים
deactivate DB

group sd Loop
AM -> AM : 2.0 בדיקה אם קיימים תורים
AM -> A : 2.1 הצגת פירוט כלל התורים
AM -> A : 2.2 הצגת ההודעה "אין תורים קיימים במערכת"
end
deactivate AM
deactivate A
@enduml